<?php
$title = 'Excluir Perfil';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Você tem certeza que vai deletar esse registro:
    <br />Nome: '<?php echo $this->escapeHtml($perfil->nome); ?>'     
</p>
<form action="<?php echo $this->basepath("application/perfil/delete/{$this->id}"); ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $perfil->id; ?>" />
    <input type="submit" name="del" value="Sim" />
    <input type="submit" name="del" value="Nao" />
</div>
</form>