<?php
$title = 'Usuarios';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table table-hover">
<tr>
    <th>nome</th>
    <th>email</th>
    <th>senha</th>
    <th>telefone</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($usuarios as $usuario) : ?>
<tr>
    <td><?php echo $this->escapeHtml($usuario->nome);?></td>
    <td><?php echo $this->escapeHtml($usuario->email);?></td>
    <td><?php echo $this->escapeHtml($usuario->senha);?></td>
    <td><?php echo $this->escapeHtml($usuario->telefone);?></td>
    <td>
        <a href="<?php echo $this->url('usuario',
            array('action'=>'edit', 'id' => $usuario->id));?>">Editar</a>
        <a href="<?php echo $this->url('usuario',
            array('action'=>'delete', 'id' => $usuario->id));?>">Deletar</a>
    </td>
</tr>
<?php endforeach; ?>
</table>