<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Times</h3>
            </div>
            <div class="panel-body">
                <a href="<?php echo $this->url('time', array('action' => 'add')); ?>">Cadastrar Time</a>

                <?php if (isset($times)) : ?>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Nome</th>
                                <th>Estado</th>
                                <th></th>
                            </tr>
                        </thead>
                        <?php foreach ($times as $time): ?>
                            <tbody>
                                <tr>
                                    <td><?php echo $time->getId(); ?></td>
                                    <td><?php echo $time->getNome(); ?></td>
                                    <td><?php echo $time->getEstado(); ?></td>
                                    <?php // \Zend\Debug\Debug::dump($time); exit; ?>
                                    <td>
                                        <a href="<?php echo $this->url('time', array('action' => 'edit', 'id' => $time->getId())); ?>">Editar</a> |
                                        <a href="<?php echo $this->url('time', array('action' => 'delete', 'id' => $time->getId())); ?>">Deletar</a>
                                    </td>
                                </tr>
                            </tbody>
                        <?php endforeach; ?>
                    </table>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
