<?php
$title = 'Usuário';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->basePath('application/usuario/add'); ?>">Cadastrar novo Usuário</a>
</p>

<table class="table table-hover">
    <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Telefone</th>
        <th>Perfil</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($usuarios as $usuario) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($usuario->nome); ?></td>
            <td><?php echo $this->escapeHtml($usuario->email); ?></td>
            <td><?php echo $this->escapeHtml($usuario->telefone); ?></td>
            <td><?php echo $this->escapeHtml($usuario->perfil->nome);?></td>
            <td>
                <a href="<?php echo $this->basepath("application/usuario/edit/" . $usuario->id); ?>">Editar</a>
            </td>
            <td>
                <a href="<?php echo $this->basepath("application/usuario/delete/" . $usuario->id); ?>">Deletar</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>