<?php
$title = 'Excluir Curso';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Você tem certeza que vai deletar esse registro:
    <br />Nome: '<?php echo $this->escapeHtml($curso->nome); ?>'
</p>
<form action="<?php echo $this->basepath("curso/index/delete/{$this->id}"); ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $curso->id; ?>" />
        <input type="submit" name="del" value="Sim" />
        <input type="submit" name="del" value="Nao" />
    </div>
</form>